apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: vote
type: Opaque
data:
  username: dXNlcg==      # 'postgres' base64 encoded
  password: cGFzc3dvcmQ=      # 'password' base64 encoded
